version: "3.9"
services:
    db:
        image: "mcr.microsoft.com/mssql/server"
        ports:
        - 1433:1433
        environment:
            SA_PASSWORD: "AE7kUbGDwyGL0NGiWYD3jFk6Nwq4qlK7BB8F5mNgCbgn6MPxAe"
            ACCEPT_EULA: "Y"